FROM jupyter/pyspark-notebook:spark-3.3.2
USER root

RUN apt-get update && apt-get install -y \
    curl
RUN pip install \
    python-dotenv==0.20.0
RUN curl https://jdbc.postgresql.org/download/postgresql-42.2.18.jar -o /opt/postgresql-42.2.18.jar
RUN curl https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar -o /opt/commons-pool2-2.11.1.jar