version: '2'

services:
  batch-processing-spark-master:
    container_name: ${SPARK_MASTER_CONTAINER_NAME}
    hostname: ${SPARK_MASTER_HOST_NAME}
    image: batch-processing/spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ../spark-scripts:/spark-scripts
      - ../scripts:/scripts
      - ../logs:/tmp
    ports:
      - ${SPARK_MASTER_UI}:8085
      - ${SPARK_MASTER_PORT}:7078

  batch-processing-spark-worker-1:
    &worker_default
    container_name: ${SPARK_WORKER_CONTAINER_NAME}-1
    image: batch-processing/spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://${SPARK_MASTER_HOST_NAME}:${SPARK_MASTER_PORT}
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ../spark-scripts:/spark-scripts
      - ../scripts:/scripts
      - ../logs:/tmp
    depends_on:
      - batch-processing-spark-master

  # batch-processing-spark-worker-2:
  #   <<: *worker_default
  #   container_name: ${SPARK_WORKER_CONTAINER_NAME}-2

networks:
  default:
    name: batch-processing-network
    external: true