services:
 batch-processing-jupyter:
  container_name: ${JUPYTER_CONTAINER_NAME}
  hostname: ${JUPYTER_CONTAINER_NAME}
  image: batch-processing/jupyter
  environment:
   - JUPYTER_ALLOW_INSECURE_WRITES=true
  ports:
   - ${JUPYTER_PORT}:8888
   - 4050:4040
   - 4051:4041
  volumes:
   - ../:/resources
   - ../notebooks:/home/jovyan/

networks:
 default:
  name: batch-processing-network
  external: true
